databases:
  - name: goalHive
    databaseName: goalHive
    user: goalHive

services:
  - type: web
    name: goalHive
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: goalHive
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false