databases:
  - name: goalHive
    databaseName: goalhive
    user: goalhive

services:
  - type: web
    name: goal_hive
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: goal_hive
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false